### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by negezor** [Aikoyori/ProgrammingVTuberLogos#1]
That looks awesome! I think you should keep it up! (and we could also add a build step to convert to Windows icons)
![image](https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/9392723/ce36c4f7-cd49-485d-b140-d30d497925e2)

**Comment by Aikoyori** [comment]
wait ayo it works as an icon wtf

**Comment by Aikoyori** [comment]
also the PNGs are provided as-is do whatever with them as long as it's under the licence

**Comment by abiriadev** [comment]
![image-8](https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/72962900/eb84d252-cadb-476e-99f0-698b207685c6)

Thank you for this awesome logo!!

do you have any plan for other IDEs too?

**Comment by Aikoyori** [comment]
I just added IntelliJ one

**Comment by supleed2** [comment]
> build step

Yeah like maybe a Powershell script that we can run after each update, would be ideal!

**Comment by abiriadev** [comment]
> > build step
> 
> Yeah like maybe a Powershell script that we can run after each update, would be ideal!

You can run imagemagick in your shell to convert to any format you want.

**Comment by cocoa-xu** [comment]
This also looks quite kawaii on macOS!!

<img width="751" alt="Screenshot 2024-04-22 at 17 24 03" src="https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/89497197/9060ca53-be61-4840-90dd-0c6d6c9385c4">
