### ISSUE TITLE
[LOGO REQUEST]  Nim (Programming Language)

### ISSUE THREAD

**Issue by xStormyy** [Aikoyori/ProgrammingVTuberLogos#107]
### Product Name

The Nim programming language

### Product Link

https://nim-lang.org/

### Other information

I would really like to know how you are doing this all with just some time left on your hand. This shit genuinely sucks and you deserves better than getting dupes.

### Select the following

All of the above.

### The following is required to submit this issue

- [X] I agree that the logo will be made available under the project's license
- [ ] Select this to have your issue immediately closed (1)
- [X] Select this no have your issue immediately closed (2)
- [ ] Select this to have your issue immediately closed (3)
- [X] Select this no have your issue immediately closed (4)
- [X] Select this no have your issue immediately closed (5)
- [X] Select this no have your issue immediately closed (6)
- [ ] Select this to have your issue immediately closed (7)
- [ ] Select this to have your issue immediately closed (8)
- [ ] Select this to have your issue immediately closed (9)
- [X] I have checked that I am not making a duplicate request (1)
- [X] I have checked that I am not making a duplicate request (2)
- [X] I have checked that I am not making a duplicate request (3)
- [ ] I have checked that I am yes making a duplicate request (4)
- [X] I have checked that I am not making a duplicate request (5)
- [ ] I have checked that I am yes making a duplicate request (6)
- [X] I have checked that I am not making a duplicate request (7)
- [X] I have checked that I am not making a duplicate request (8)
- [ ] I have checked that I am yes making a duplicate request (9)
- [X] I have checked that I am not making a duplicate request (10)
- [X] I have checked that I am not making a duplicate request (11)
- [ ] I have checked that I am yes making a duplicate request (12)
- [ ] I have checked that I am yes making a duplicate request (13)
- [X] I have checked that I am not making a duplicate request (14)
- [X] I have checked that I am not making a duplicate request (15)
- [X] I have checked that I am not making a duplicate request (16)
- [ ] I have checked that I am yes making a duplicate request (17)
- [X] I have checked that I am not making a duplicate request (18)
- [ ] I have checked that I am yes making a duplicate request (19)
- [X] I have checked that I am not making a duplicate request (20)
- [ ] I have checked that I am yes making a duplicate request (21)
- [ ] I have checked that I am yes making a duplicate request (22)
- [ ] I have checked that I am yes making a duplicate request (23)
- [X] I have checked that I am not making a duplicate request (24)
- [ ] I have checked that I am yes making a duplicate request (25)
- [X] I have checked that I am not making a duplicate request (26)
- [ ] I have checked that I am yes making a duplicate request (27)
- [X] I have checked that I am not making a duplicate request (28)
- [X] I have checked that I am not making a duplicate request (29)
- [ ] I have checked that I am yes making a duplicate request (30)
- [ ] I have checked that I am yes making a duplicate request (31)
- [X] I have checked that I am not making a duplicate request (32)
- [ ] I genuinely did not give a single damn if this gets rejected because I did not read any single thing and just blindly click every checkbox.
- [X] If this turns out to be a duplicate, I agree that I will be burned at stake and publicly shamed until the project maintainer deems enough
- [X] If this turns out to be a duplicate, I agree that I will have my access from the repository revoked.

**Comment by Aikoyori** [comment]
please refile the issue

**Comment by xstyyy** [comment]
Small update:
Someone else has made a vtuber logo for nim

https://gist.github.com/ZoomTen/073a2e07eea88b7462135d3679c793b0
