### ISSUE TITLE
[ON STAKE] Jenkins

### ISSUE THREAD

**Issue by hervelemeur** [Aikoyori/ProgrammingVTuberLogos#108]
- [X] If this turns out to be a duplicate, I agree that I will be burned at stake and publicly shamed until the project maintainer deems enough
- [X] If this turns out to be a duplicate, I agree that I will have my access from the repository revoked.

![image](https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/52448671/8e82e522-9799-4c55-bac3-42588d5feec4)

**Comment by dgw** [comment]
> - [X] If this turns out to be a duplicate, I agree that I will be burned at stake and publicly shamed until the project maintainer deems enough
> - [X] If this turns out to be a duplicate, I agree that I will have my access from the repository revoked.

RIP OP (#101)

**Comment by hervelemeur** [comment]
Damn 😓 🤦
