### ISSUE TITLE
[OTHER] SAWARATSUKI/ServiceLogos not available as of now

### ISSUE THREAD

**Issue by weareblahs** [Aikoyori/ProgrammingVTuberLogos#192]
Seems like the linked link for "sawaratsuki1004's transparent logos" (https://github.com/SAWARATSUKI/ServiceLogos) on the "Similar Projects" part of the README.md file is invalid as of today (May 6, 2024). Please check.

**Comment by kamikyoku** [comment]
The repo was privated to "clean things up", if you haven't caught up with the situation.

**Comment by Aikoyori** [comment]
I already talked to them about this.

**Comment by kamikyoku** [comment]
Wait, is that so? I feel bad for them to be honest.
