### ISSUE TITLE
[LOGO REQUEST] PHP

### ISSUE THREAD

**Issue by Renyu106** [Aikoyori/ProgrammingVTuberLogos#37]
### Product Name

PHP

### Product Link

https://www.php.net/

### The following is required to submit this issue

- [X] I agree that the logo will be made available under the project's license
- [X] I have checked that I am not making a duplicate request

**Comment by Aikoyori** [comment]
personal home page moment

**Comment by Renyu106** [comment]
I just saw the PHP logo added to the new [repo](https://github.com/SAWARATSUKI/ServiceLogos/tree/main/PHP)!
Thank you very much ！！ 🙇 🤍
