### ISSUE TITLE
[OTHER] Font of these logos

### ISSUE THREAD

**Issue by F1Justin** [Aikoyori/ProgrammingVTuberLogos#52]
## Describe your issues here
I wonder what's the font of these logos, they are really interesting.

**Comment by supleed2** [comment]
Mentioned in #5 it seems to be Yuruka, I think [this one](https://www.onlinewebfonts.com/download/2b3966678f6a1c8c8be202caeb49d95a)?

**Comment by F1Justin** [comment]
> Mentioned in #5 it seems to be Yuruka, I think [this one](https://www.onlinewebfonts.com/download/2b3966678f6a1c8c8be202caeb49d95a)?

Thank you!
