### ISSUE TITLE
[LOGO REQUEST] NeoVim

### ISSUE THREAD

**Issue by BestInfinity** [Aikoyori/ProgrammingVTuberLogos#59]
### Product Name

NeoVim/Vim

### Product Link

https://github.com/neovim/neovim

### The following is required to submit this issue

- [X] I agree that the logo will be made available under the project's license
- [X] I have checked that I am not making a duplicate request

**Comment by AlphaNecron** [comment]
[main/Neovim](https://github.com/Aikoyori/ProgrammingVTuberLogos/tree/main/Neovim)

**Comment by Aikoyori** [comment]
is brother serious
