### ISSUE TITLE
PaperMC logo

### ISSUE THREAD

**Issue by minhh2792** [Aikoyori/ProgrammingVTuberLogos#6]
PaperMC logo with Paper-chan would be nice
https://paper-chan.moe/paper-chan-project/

**Comment by SinonCute** [comment]
+1 ❤️

**Comment by AlphaNecron** [comment]
-100 :trollface:

**Comment by QuanTrieuPCYT** [comment]
what the heck it's real

**Comment by Aikoyori** [comment]
:trollface:

**Comment by Aikoyori** [comment]
eed68cfc3fe5b43cc1c01cee286d5d3fc328ded1
