### ISSUE TITLE
[README] Add Visual Studio IDE Logo to similar list

### ISSUE THREAD

**Issue by hvpexe** [Aikoyori/ProgrammingVTuberLogos#76]
### Your Repo Link

https://github.com/hvpexe/ProgrammingVTuberLogos-VisualStudio

### Other information

Please credit **Manhkbrady**, not me (hvpexe)
btw, I'm the one who requested [Docker Logo](https://github.com/Aikoyori/ProgrammingVTuberLogos/issues/8)

### The following is required to submit this issue

- [x] I have checked that I am not making a duplicate request

**Comment by Aikoyori** [comment]
Fixed in 763f85718f7a522fb893731fdb787878c9943116

**Comment by Aikoyori** [comment]
oh nvm ill change the credit

**Comment by hvpexe** [comment]
thank you so much
