### ISSUE TITLE
[LOGO REQUEST] Godot

### ISSUE THREAD

**Issue by Lisieshy** [Aikoyori/ProgrammingVTuberLogos#79]
### Product Name

Godot

### Product Link

https://godotengine.org

### The following is required to submit this issue

- [X] I agree that the logo will be made available under the project's license
- [X] I have checked that I am not making a duplicate request

**Comment by Lisieshy** [comment]
whoops I did not see it was already done because GitHub mobile wasn't showing all folders. Sorry for the spam!

**Comment by fagirton** [comment]
The Godot logo is extremely cool and all, but is there a way to replace it inside of actual Godot app? 
There seems to be zero info about it and in the source code it feels like engine has boot splashes built inside of the executable.
