### ISSUE TITLE
Docker logo

### ISSUE THREAD

**Issue by hvpexe** [Aikoyori/ProgrammingVTuberLogos#8]
It would be nice if you make Docker logo

**Comment by Aikoyori** [comment]
<img width="836" alt="image" src="https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/12034280/a4977a31-50e5-499e-9f20-43dc4a2f339e">
me channelling my energy to add whatever i can to the logo

**Comment by Aikoyori** [comment]
![image](https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/12034280/6afc5cd8-dbba-4fbc-84f6-d9cfef9537df)
i am happier

**Comment by Aikoyori** [comment]
<img width="833" alt="image" src="https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/12034280/a6087ce0-7a68-4640-90e7-81f66f4c5034">
sorry wrong image lol

**Comment by hvpexe** [comment]
Great work 👍
