### ISSUE TITLE
[LOGO REQUEST] ImHex

### ISSUE THREAD

**Issue by WerWolv** [Aikoyori/ProgrammingVTuberLogos#80]
### Product Name

ImHex

### Product Link

https://imhex.werwolv.net

### Other information

Hey! I'd love to use one of your logos for the welcome screen banner of ImHex

ImHex is an advanced Hex Editor with lots of analysis features. Things like binary and hexadecimal numbers in the general style of your VS Code logo would look amazing I think.

<details>
  <summary><strong>Some screenshots of ImHex</strong></summary>

![Welcome Screen](https://github.com/Aikoyori/ProgrammingVTuberLogos/assets/10835354/ea67b74b-cbbd-403e-b253-7b1b5f1c14db)

![Hex editor, patterns and data information](https://github.com/WerWolv/ImHex/assets/10835354/4f358238-2d27-41aa-9015-a2c6cc3708cf)
![Bookmarks, disassembler and data processor](https://github.com/WerWolv/ImHex/assets/10835354/183bc2cc-2439-4ded-b4c5-b140e19fc92f)
![Data Processor decrypting some data and displaying it as an image](https://github.com/WerWolv/ImHex/assets/10835354/d0623081-3094-4840-a8a8-647b38724db8)
![STL Parser written in the Pattern Language visualizing a 3D model](https://github.com/WerWolv/ImHex/assets/10835354/62cbcd18-1c3f-4dd6-a877-2bf2bf4bb2a5)
![Data Information view displaying various stats about the file](https://github.com/WerWolv/ImHex/assets/10835354/d4706c01-c258-45c9-80b8-fe7a10d5a1de)
</details

### The following is required to submit this issue

- [X] I agree that the logo will be made available under the project's license
- [X] I have checked that I am not making a duplicate request

**Comment by Aikoyori** [comment]
it is technically done i am awaiting confirmation

**Comment by hifiveszu** [comment]
> where the image? 图像在哪里？

@AdonNeet  😂  https://github.com/Aikoyori/ProgrammingVTuberLogos/tree/main/ImHex

**Comment by AdonNeet** [comment]
> > where the image? 图像在哪里？
> 
> @AdonNeet  😂  https://github.com/Aikoyori/ProgrammingVTuberLogos/tree/main/ImHex


Ok :v
