### ISSUE TITLE
Link to repo with Kate

### ISSUE THREAD

**Issue by G2-Games** [Aikoyori/ProgrammingVTuberLogos#9]
Would you consider linking to my repository which has (currently, might add more) a logo for the Kate editor?

Link: https://github.com/G2-Games/fun-logos

If not, no worries.

**Comment by PetricaT** [comment]
Oh dude that's awesome, it looks soooooo good! I'm going to add a link to your repository to mine so people can find it trough me too!

**Comment by G2-Games** [comment]
That's awesome, thank you!

**Comment by Aikoyori** [comment]
I'll link them when I make the neovim logo

**Comment by G2-Games** [comment]
Awesome, thanks! Your VSCode logo inspired me to make one for Kate, I think it's really cool.

**Comment by Aikoyori** [comment]
0fe1c1f14c181632016e6058c67eaa0aca610883
